# http://localhost:8080/actuator/gateway/routes
server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
#    spring.application.name=apigateway
  application:
    name: apigateway
  cloud:
    # A client sends a request to Spring Cloud Gateway. If the request matches a route through its predicates, the Gateway HandlerMapping will send the request to the Gateway WebHandler, which in turn will run the request through a chain of filters.
    gateway:
      # For automatic route discovery through Eureka
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      # Route. It’s identified by a unique ID, a collection of predicates deciding whether to follow the route, a URI for forwarding the request if the predicates allow, and a collection of filters applied either before or after forwarding the request downstream.
      routes:
        - id: usermsclient
          uri: lb://USERMS-CLIENT
          # Predicate. It matches anything from the HTTP request, including path, host, headers, query parameters, cookies, and body.
          predicates:
            - Path=/dummy-client/**
          # Filter. It modifies an HTTP request or response before or after forwarding the request to the downstream service.
          filters:
            - RewritePath=/dummy-client/(?<path>.*), /$\{path}

        - id: usermsmodule
          uri: lb://USERMS
          predicates:
            - Path=/dummy/**
          filters:
            - RewritePath=/dummy/(?<path>.*), /$\{path}
        - id: ordermsmodule
          uri: lb://ORDERMS
          # http://localhost:8080/dummy-orderms/orders
          # orderms: http://localhost:8082/orders
          # http://localhost:8080/dummy-orderms/orders/orderId
          # orderms: http://localhost:8082/orders/orderId
          predicates:
            - Path=/dummy-orderms/**
          filters:
            - RewritePath=/dummy-orderms/(?<path>.*), /$\{path}
# http://localhost:8080/actuator/gateway/routes
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.edu: DEBUG